# Based on pydata/xarray
codecov:
  require_ci_to_pass: no

coverage:
  status:
    project:
      default:
        target: 85
    patch: false
    changes: false

comment:
  layout: diff, flags, files
  behavior: once
  require_base: no
